---
- hosts: '{{ target }}'
  gather_facts: "no"
  become: true

  tasks:
    - name: Install the latest version of vagrant and ansible
      dnf:
        name: 
          - bridge-utils 
          - libvirt 
          - virt-install 
          - qemu-kvm
          - libvirt-devel 
          - virt-top 
          - libguestfs-tools
          - ansible

        state: present

    - name: Install virt manager vagrant
      dnf:
        name: 
          - virt-manager
          - vagrant
          - gcc 
          - libvirt 
          - libvirt-devel 
          - libxml2-devel 
          - make 
          - ruby-devel
        state: present

    - name: initiliaze vagrant plugin
      shell: vagrant plugin install vagrant-libvirt
      
    - name: initiliaze vagrant plugin mutate
      shell: vagrant plugin install vagrant-mutate

    - name: initiliaze vagrant plugin scp for copying for public key
      shell: vagrant plugin install vagrant-scp

    - name: fix config to root user
      replace:
        path: /etc/libvirt/qemu.conf
        regexp: '\#user = "root"'
        replace: 'user = "root"'

    - name: Fix Config to root user
      replace:
        path: /etc/libvirt/qemu.conf
        regexp: '\#group = "root"'
        replace: 'group = "root"'

    - name: start virtual system
      systemd:
        state: restarted
        enabled: true
        name: libvirtd


    - name: Create root folder for Kubernetes main vagrant
      file:
        path: /home/vagrant
        state: directory
        mode: '0755'


    - name: Create master kubernetes node for vagrant folder
      file:
        path: /home/vagrant/master
        state: directory
        mode: '0755'

    - name: Create node kubernetes for vagrant folder
      file:
        path: /home/vagrant/node
        state: directory
        mode: '0755'

    - name: Copy over Vagrant Files for master kubernetes
      template:
        src: Vagrantfile_master.j2
        dest: /home/vagrant/master/Vagrantfile
        owner: root
        group: root
        mode: '0644'

    - name: copy over vagrant files for node kubernetes
      template:
        src: Vagrantfile_node.j2
        dest: /home/vagrant/node/Vagrantfile
        owner: root
        group: root
        mode: '0644'

    - name: start it up master
      shell: cd /home/vagrant/master && vagrant destroy --force ; vagrant up && vagrant ssh -c  "sudo yum -y install ansible"

    - name: start it up node
      shell: cd /home/vagrant/node && vagrant destory --force ;vagrant up && vagrant ssh -c  "sudo yum -y install ansible"

    - name: copy pub key over for calling ansible on host for master 
      shell: cd /home/vagrant/master && sudo vagrant scp /home/vagrant/.ssh/id_rsa.pub /home/vagrant/

    - name: copy pub key over for calling ansible on host for node
      shell: cd /home/vagrant/node && vagrant scp /home/vagrant/.ssh/id_rsa.pub /home/vagrant/

    - name: add key to public ssh for master
      shell: cd /home/vagrant/master && vagrant ssh -c "cat /home/vagrant/id_rsa.pub /home/vagrant/.ssh/authorized_keys > /home/vagrant/.ssh/authorized_keys2 && cp /home/vagrant/.ssh/authorized_keys2 /home/vagrant/.ssh/authorized_keys"

    - name: add key to public ssh for node
      shell: cd /home/vagrant/node && vagrant ssh -c "cat /home/vagrant/id_rsa.pub /home/vagrant/.ssh/authorized_keys > /home/vagrant/.ssh/authorized_keys2 && cp /home/vagrant/.ssh/authorized_keys2 /home/vagrant/.ssh/authorized_keys"








