---
- hosts: '{{ target }}'
  gather_facts: "no"
  become: true
  tasks:
    - name: create felix config
      copy:
        content: |
          apiVersion: projectcalico.org/v3
          kind: FelixConfiguration
          metadata:
            name: default
          spec:
            ipipEnabled: Always
            logSeverityScreen: Info
            reportingInterval: 0s
        dest: /tmp/felixconfig
        force: no
        group: root
        owner: root
        mode: 0555

    - name: Initialize the Kubernetes cluster using kubeadm
      command:
        cmd:  sudo sh -c "KUBECONFIG=/etc/kubernetes/admin.conf DATASTORE_TYPE=kubernetes /opt/cni/bin/calicoctl apply -f /tmp/felixconfig"
        creates: /tmp/felixconfigured

    - name: save state file
      copy:
        content: ""
        dest: /tmp/felixconfigured
        force: no
        group: root
        owner: root
        mode: 0555