---
- hosts: 127.0.0.1
  connection: local
  vars:
    BUCKET: "{{ lookup('env','BUCKET') }}"
    AWS_FIRST_REGION: "{{ lookup('env','AWS_FIRST_REGION') }}"
    AWS_SECOND_REGION: "{{ lookup('env','AWS_SECOND_REGION') }}"
    DOMAIN: "{{ lookup('env','DOMAIN') }}"
    VPC_RANGE: "{{ lookup('env','VPC_RANGE') }}"
    IP_PUBILC_RANGE: "{{ lookup('env','IP_PUBILC_RANGE') }}"
    IP_PRIVATE_RANGE: "{{ lookup('env','IP_PRIVATE_RANGE') }}"
    TYPE_EC2_INSTANCE: "{{ lookup('env','TYPE_EC2_INSTANCE') }}"
    HARD_DISK_SIZE: "{{ lookup('env','HARD_DISK_SIZE') }}"
    RED_HAT_IMAGE_AMI: "{{ lookup('env','RED_HAT_IMAGE_AMI') }}"
    NODE_AMOUNT: "{{ lookup('env','NODE_AMOUNT') }}"
    WORKSPACE: "{{ lookup('env','WORKSPACE') }}"
    KEY_NAME_DEPLOYER: "{{ lookup('env','KEY_NAME_DEPLOYER') }}"
    SECURITY_GROUP_GLOBAL: "{{ lookup('env','SECURITY_GROUP_GLOBAL') }}"
    PRIVATE_SUBNET: "{{ lookup('env','PRIVATE_SUBNET') }}"
    IP_PRIVATE_RANGE: "{{ lookup('env','IP_PRIVATE_RANGE') }}"
    IAM_INSTANCE_PROFILE: "{{ lookup('env',' IAM_INSTANCE_PROFILE') }}"

  tasks:

  - debug: msg="Creating Terraform files on jenkins "

  - name: create folders
    file:
      path: "{{ WORKSPACE }}/terraform_node/"
      state: directory

  - name: Creating from template node for terraform to init
    template:
      src: "{{ WORKSPACE }}/templates/kubernetes_node.j2"
      dest: "{{  WORKSPACE }}/terraform_node/kubernetes_node.tf"