---
- hosts: '{{ target }}'
  gather_facts: "no"
  become: true

  tasks:
    - name: Add cents repo
      yum_repository:
        name: maincentos
        description:  enabled centos due to repo issues
        baseurl: http://mirror.centos.org/centos/7/extras/x86_64/
    - name: Install required system packages
      yum:
        name:
          - avahi
          - python3-pip
          - curl
          - squid

    - name: Explicitly specifying named matched groups
      replace:
        destfile: /etc/squid/squid.conf
        regexp: "^http_access allow localhost$"
        replace: http_access allow localnet

    - name: Make sure a service is running
      systemd:
        state: restarted
        name: squid