---
- hosts: '{{ target }}'
  gather_facts: "no"
  become: true
  tasks:

    - name: Creates specific folders
      file:
        path:  /etc/cni/net.d/
        state: directory

    - name: Creates directory
      file:
        path: /opt/cni/bin/
        state: directory


    - name: Creates specific folders
      file:
        path: /etc/ssl/csr/
        state: directory

    - name: Creates specific folders
      file:
        path: /etc/ssl/private/
        state: directory

    - name: Initialize the Kubernetes cluster using kubeadm
      command:
        cmd: openssl req -newkey rsa:4096 -keyout /etc/ssl/private/cni.key -nodes -out /etc/ssl/csr/cni.csr -subj "/CN=calico-cni"
        creates: /tmp/cniinstalled

    - name: Initialize the Kubernetes cluster using kubeadm
      command:
        cmd: openssl x509 -req -in /etc/ssl/csr/cni.csr -CA /etc/kubernetes/pki/ca.crt -CAkey /etc/kubernetes/pki/ca.key -CAcreateserial -out /etc/kubernetes/pki/cni.crt -days 365
        creates: /tmp/cniinstalled

    - name: Initialize the Kubernetes cluster using kubeadm
      command:
        cmd:  sudo sh -c "kubectl config set-credentials calico-cni --client-certificate=/etc/kubernetes/pki/cni.crt --client-key=/etc/ssl/private/cni.key --embed-certs=true --kubeconfig=/tmp/cni.kubeconfig"
        creates: /tmp/cniinstalled

    - name: Initialize the Kubernetes cluster using kubeadm
      command:
        cmd:  sudo sh -c "kubectl config set-context default --cluster=kubernetes --user=calico-cni --kubeconfig=/tmp/cni.kubeconfig"
        creates: /tmp/cniinstalled

    - name: Initialize the Kubernetes cluster using kubeadm
      command:
        cmd:  sudo sh -c "kubectl config use-context default --kubeconfig=/tmp/cni.kubeconfig"
        creates: /tmp/cniinstalled

    - file:
        path: /tmp/rbacalico.sh
        state: touch
        mode: "u+rwx,g+rx,o+rx"

    - name: Initialize the Kubernetes cluster using kubeadm
      command:
        cmd:  sudo sh -c "/tmp/rbacalico.sh"
        creates: /tmp/cniinstalled

    - name: Initialize the Kubernetes cluster using kubeadm
      get_url:
        url: https://github.com/projectcalico/cni-plugin/releases/download/v3.14.0/calico-amd64
        dest: /opt/cni/bin/calico
        mode: '0775'
      environment:
        http_proxy: '{{ http_ansible_proxy }}'
        https_proxy: '{{ http_ansible_proxy }}'


    - name: Initialize the Kubernetes cluster using kubeadm
      get_url:
        url: https://github.com/projectcalico/cni-plugin/releases/download/v3.14.0/calico-ipam-amd64
        dest: /opt/cni/bin/calico-ipam
        mode: '0775'
      environment:
        http_proxy: '{{ http_ansible_proxy }}'
        https_proxy: '{{ http_ansible_proxy }}'

    - name: Initialize the Kubernetes cluster using kubeadm
      get_url:
        url:  https://github.com/projectcalico/calicoctl/releases/download/v3.17.1/calicoctl
        dest: /opt/cni/bin/calico-ipam
        mode: '0775'
      environment:
        http_proxy: '{{ http_ansible_proxy }}'
        https_proxy: '{{ http_ansible_proxy }}'

    - name: Initialize the Kubernetes cluster using kubeadm
      command:
        cmd:  cp /tmp/cni.kubeconfig /etc/cni/net.d/calico-kubeconfig
        creates: /tmp/cniinstalled

    - name: Creating a file with content
      copy:
        dest: "/etc/systemd/system/rc-local.service"
        content: |
          {
            "name": "k8s-pod-network",
            "cniVersion": "0.3.1",
            "plugins": [
            {
                "type": "calico",
                "log_level": "info",
                "datastore_type": "kubernetes",
                "mtu": 1500,
                "ipam": {
                    "type": "calico-ipam"
                },
                 "policy": {
                        "type": "k8s"
                  },
                "kubernetes": {
                    "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
                        }
                    },
                {
             "type": "portmap",
            "snat": true,
                "capabilities": {"portMappings": true}
            }
            ]
          }

    - name: create passing file
      copy:
        content: ""
        dest: /tmp/cniinstalled
        force: no
        group: root
        owner: root
        mode: 0555




